data:
  base_dir: RSA_deep_working/Data
  patch_size: 512
  batch_size: 128
  save_path: Results/Reconstruction/

training:
  epochs: 300
  epochs_btw_eval: 1
  device: cuda
  save_best_only: true
  early_stopping:
    metric: f1_score
    patience: 5
    delta: 0.01
  lr_scheduler:
    name: ReduceLROnPlateau
    mode: min
    factor: 0.5
    patience: 5
  checkpoint_dir: RSA_deep_working/Models/Checkpoints
  log_dir: RSA_deep_working/Models/Logs


model:
  name: Unet
  pretrained: false
  params:
    in_channels: 1
    out_channels: 1
    encoder_name: efficientnet-b0
    encoder_weights: null
    decoder_attention_type: null
    return_logits: False

optimizer:
  name: Adam
  learning_rate: 0.09562894104741092
  weight_decay: 5.469605033039051e-07

loss:
  name: bce
  params:
    weight: null
    reduction: mean

metrics:
  threshold_4_binarize: 0.5 # to change manually in the code of each metric
  gpu:
    - { name: "dice" }
    - { name: "cldice" }
    - { name: "f1_score" }
    - { name: "f_2_score" }
    - { name: "f_3_score" }
    - { name: "f_4_score" }
    - { name: "iou" }
    - { name: "mean_iou" }
    - { name: "normalized_mutual_information" }
    - { name: "pixel_accuracy" }
    - { name: "precision" }
    - { name: "recall" }
    - { name: "specificity" }
    - { name: "betti0_abs_err_gpu" }
    - { name: "betti0_relative_error_gpu" }
    - { name: "betti0_variation_index_gpu" }
    - { name: "betti1_abs_err_gpu" }
    - { name: "betti1_relative_error_gpu" }
    - { name: "betti1_variation_index_gpu" }
    - { name: "hausdorff_distance95" }
    - { name: "hausdorff_distance" }
    
  cpu:
    - { name: "average_symetric_centerline_distance" }

metrics_graph:
  threshold_4_binarize: 0.5
  per_plant:
    - name: "number_of_organs_ratio"
    - name: "total_root_length_distances"
    - name: "area_convex_hull_ratio"
    - name: "area_below_intercept"
    - name: "dtw_below_intercept"
    - name: "euclidian_btw_intercepts"
  per_box:
    - name: "number_of_organs_ratio"
    - name: "number_of_organs_recall"
    - name: "number_of_organs_precision"
    - name: "number_of_organs_f1"
    - name: "number_of_plants_ratio"
    - name: "total_root_length_distances"

measures:
  threshold_4_binarize: 0.5
  per_plant:
    - name: "number_of_organs"
    - name: "total_root_length"
    - name: "number_of_laterals"
    #- name: "intercept_curve_area"
    - name: "convex_area_hull"
    - name: "root_density"
    - name: "primary_root_length"
    - name: "lateral_root_length"
  per_box:
    - name: "number_of_plants"
    - name: "number_of_organs"
    - name: "total_root_length"
    - name: "number_of_laterals"

rst:
  jar_path: RootSystemTracker/target/rootsystemtracker-1.6.1-jar-with-dependencies.jar
