data:
  base_dir: RSA_deep_working/Data
  patch_size: 512
  batch_size: 128
  save_path: Results/Reconstruction/

training:
  epochs: 300
  epochs_btw_eval: 1
  device: cuda
  save_best_only: true
  early_stopping:
    metric: f1_score
    patience: 5
    delta: 0.01
  lr_scheduler:
    name: ReduceLROnPlateau
    mode: min
    factor: 0.5
    patience: 5
  checkpoint_dir: RSA_deep_working/Models/Checkpoints
  log_dir: RSA_deep_working/Models/Logs


model:
  name: Unet
  pretrained: false
  params:
    in_channels: 1
    out_channels: 1
    encoder_name: efficientnet-b0
    encoder_weights: null
    decoder_attention_type: null
    return_logits: False

optimizer:
  name: Adam
  learning_rate: 0.00014010700505126466
  weight_decay: 6.780461607194574e-06

loss:
  name: dice
  params:
    weight: null
    reduction: mean

metrics:
  threshold_4_binarize: 0.5 # to change manually in the code of each metric
  gpu:
    - { name: "dice" }
    - { name: "cldice" }
    - { name: "focal_loss" }
    - { name: "f1_score" }
    - { name: "hausdorff_distance" }
    - { name: "mean_iou" }
    - { name: "normalized_mutual_information" }
    - { name: "pixel_accuracy" }
    - { name: "precision" }
    - { name: "recall" }
    - { name: "specificity" }
    - { name: "betti0_jaccard_ratio_gpu" }
    - { name: "betti0_relative_error_gpu" }
    - { name: "betti0_variation_index_gpu" }
    - { name: "betti1_jaccard_ratio_gpu" }
    - { name: "betti1_relative_error_gpu" }
    - { name: "betti1_variation_index_gpu" }
    - { name: "centerline_f1_gpu" }
    - { name: "persistence_bottleneck_gpu" }
    - { name: "persistence_wasserstein_gpu" }
    - { name: "average_centerline_distance" }
    - { name: "average_path_length_similarity" }
    #- { name: "branch_break_rate" }
    #- { name: "branch_length_rate" }
    #- { name: "surface_dice" }
    #- { name: "surface_distance" }
  cpu:
    - { name: "variation_of_information" }
    #- { name: "betti0_jaccard_ratio" }
    #- { name: "betti0_relative_error" }
    #- { name: "betti0_variation_index" }
    #- { name: "betti1_jaccard_ratio" }
    #- { name: "betti1_relative_error" }
    #- { name: "betti1_variation_index" }
    #- { name: "euler_charac_jaccard_ratio" }
    #- { name: "euler_charac_relative_error" }
    #- { name: "euler_charac_variation_index" }
    #- { name: "persistence_bottleneck" }
    #- { name: "persistence_wasserstein" }

measures:
  threshold_4_binarize: 0.5
  per_plant:
    - name: "number_of_organs"
    - name: "total_root_length"
    - name: "number_of_laterals"
    - name: "intercept_curve_area"
    - name: "convex_area_hull"
    - name: "root_density"
    - name: "primary_root_length"
    - name: "lateral_root_length"
  per_box:
    - name: "number_of_plants"
    - name: "number_of_organs"
    - name: "total_root_length"
    - name: "number_of_laterals"
    
rst:
  jar_path: RootSystemTracker/target/rootsystemtracker-1.6.1-jar-with-dependencies.jar
